#!/usr/bin/env bash
# This is a Bash script that displays numbers from 1 to 100.
  # FizzBuzz when the number is a multiple of 3 and 5
  # Fizz when the number is multiple of 3
  # Buzz when the number is a multiple of 5
  # Otherwise, displays the number
  # In a list format

for (( x = 1; x <= 100; x++ ))
do
    if (( x % 3 == 0 && x % 5 == 0 ))
    then
	echo "FizzBuzz"
    elif (( x % 3 == 0 ))
    then
	echo "Fizz"
    elif (( x % 5 == 0 ))
    then
	echo "Buzz"
    else
	echo "$x"
    fi
done
