#!/usr/bin/env bash
# This is a Bash script that displays the content of the file /etc/passwd.
  # using while loop, the script should only display:
  # username
  # user id
  # Home directory path for the user

while read -r line; do
    echo "$line" | cut -d ':' -f 1,3,6
done</etc/passwd
