#!/usr/bin/env bash
# This is a Bash script that sorts visitor IP along with the HTTP status code from the Apache log file and prints the Data.

awk -F' ' '{ print $1, $9 }' apache-access.log | sort | uniq -c | sort -rn
