#!/usr/bin/env bash
# This Bash script displays numbers from 1 to 20 and does the following:
# - Prints "4" and "bad luck from China" for the 4th loop iteration.
# - Prints "9" and "bad luck from Japan" for the 9th loop iteration.
# - Prints "17" and "bad luck from Italy" for the 17th loop iteration.

x=1

while [ $x -le 20 ]
do
    echo $x
    case $x in
        4) echo "Bad luck from China"
            ;;
        9) echo "Bad luck from Japan"
            ;;
        17) echo "Bad luck from Italy"
            ;;
        esac
    x=$((x+1))
done

