#!/usr/bin/env bash
# This Bash script displays the content of the current directory in a list format,
# where only the part of the name after the first dash is displayed.

for f in *
do
	if [[ -f $f && $f != .* && $ =~ ^[^-]*- ]]
	then
		 echo "${f#*-}"
	fi
done

